#!/bin/sh
#### This is a horrible kludge. Should be part of first boot process, using UCI the right way.
#### Fails to delete files which helps debugging but will eventually fill disk.

## This script: enters the MAC of the WIFI into /config/wireless to avoid phy0 failures.
##Sets up IP addresses based on MAC addresses, mostly like commotionwireless.

cd /etc/config
mkdir -p ./tmp

# find macs
wlanmac=`cat /sys/class/ieee80211/phy0/macaddress`

test=`grep MESHIP ./network`
if [ "0" = $? ]; then

    apE=`dd if=/dev/urandom bs=5 count=1 | hexdump -e '1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X"'`
  meshE=`dd if=/dev/urandom bs=5 count=1 | hexdump -e '1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X"'`

#mesh= last 3 bytes of mac
  meship=`echo $meshE  |awk -F: '{ p3=("0x" substr($3,0,2))+0 ; p4=("0x" substr($4,0,2))+0  ;\
         p5=("0x" substr($5,0,2))+0; ;printf "%d.%d.%d",p3,p4,p5 }' `

# ap is last 2 of mac, followed by .1
  apip=`echo $apE  |awk -F: '{ p4=("0x" substr($4,0,2))+0 ; p5=("0x" substr($5,0,2))+0  ;printf "%d.%d.1",p4,p5 }' `
  echo $meship $meshE $apE $apip


  sed -e s/MESHIP/$meship/g -e s/APIP/$apip/g -e s/MESHETHER/$meshE/g  -e s/APETHER/$apE/g < ./network > .
/tmp/network.$$
  cp network ./tmp/network.orig
  mv ./tmp/network.$$ /etc/config/network

fi

# now fix irritating hardware phy0 problem.
test=`grep MPMAC wireless`
if [ "0" = $? ]; then
# I'm sure there's a correct openwrt idiom for this  - oh well
  sed -e s/MPMAC/$wlanmac/g < ./wireless > ./tmp/wireless.$$
  cp wireless ./tmp/wireless.orig
  mv ./tmp/wireless.$$ /etc/config/wireless
fi
