#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=41

start() {
  mkdir -p /serval /serval-var /dos
  mount /dev/sda1 /dos

  if [ -f /dos/serval/readme.txt ]; then
        mount /dev/sda2 /serval
        mount /dev/sda3 /serval-var

  else
        echo "reformatting usb"
	umount /dev/sda1 /dos
        killall runservald
        export SERVALINSTANCE_PATH=/etc/serval
        servald stop

        /bin/sh /etc/serval/scripts/run-fdisk.sh
  fi




  if [ -x /dos/serval/serval.sh ]; then
        /bin/sh /dos/serval/serval.sh start
  else
        export SERVALINSTANCE_PATH=/etc/serval
        mkdir -p $SERVALINSTANCE_PATH
        /etc/serval/runservald &
  fi
}

stop() {
  if [ -x /dos/serval/serval.sh ]; then
	/bin/sh /dos/serval/serval.sh stop
  else 
	export SERVALINSTANCE_PATH=/etc/serval
  	servald stop
  fi
}
