#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=41

start() {
  # Start servald
#Would rather do this with hotplug on MP2 
 # mount /dev/sda1 /dos
 # mount /dev/sda2 /serval
 # mount /dev/sda3 /serval-var
# if mount has failed, we're going to fill up flash eventually
  mkdir -p /serval /serval-var /dos

  export SERVALINSTANCE_PATH=/etc/serval
  mkdir -p $SERVALINSTANCE_PATH
  /etc/serval/runservald &
}

stop() {
  export SERVALINSTANCE_PATH=/etc/serval
  servald stop
}
